### ISSUE TITLE
[Bug Report] Disappearing Firefly (Entity Distance Error?)

### ISSUE THREAD

**Issue by cymophic** [Ineffa/Wondrous-Wilds#5]
Apparently, fireflies disappear when you move further away - the effect when you have a short entity distance. However, I checked my settings and my entity distance is set to default (100%), and I can see other mobs are fine even if I go much further compared to the distance where my fireflies disappear.

**Comment by NeffaDev** [comment]
Are they unrendering or just despawning? If you're referring to how they despawn at a shorter distance than most other mobs, that is intentional. It's meant to serve as a way to help keep them closer around players more consistently.

**Comment by cymophic** [comment]
Thank you for the reply. Yes, I noticed that they un-render at a shorter distance compared to other mobs. However, if it's intentional, I have no problems then. Does that mean that it serves as a border for them?

**Comment by NeffaDev** [comment]
Yes, the radius in which they can spawn and despawn outside of is smaller than most other mobs because it makes them spawn closer to players, and it also helps prevent them from lingering overly far away. I did it this way because you normally would want them to stay nearby since they are meant to provide ambience.

I assume that mechanic is what you're experiencing, and if so then yes it is intentional and shouldn't be a concern.
