### ISSUE TITLE
Crash with latest two versions of GeckoLib

### ISSUE THREAD

**Issue by gabriel-andreescu** [Ineffa/Wondrous-Wilds#8]
geckolib-fabric-1.19-3.1.26 works fine, anything above crashes

[crash-2022-10-26_21.33.58-client.txt](https://github.com/Ineffa/Wondrous-Wilds/files/9872819/crash-2022-10-26_21.33.58-client.txt)
[crash-2022-10-26_21.35.24-client.txt](https://github.com/Ineffa/Wondrous-Wilds/files/9872820/crash-2022-10-26_21.35.24-client.txt)

**Comment by NeffaDev** [comment]
GeckoLib made some major and SEVERELY broken changes in version 3.1.28, which are impossible for me to fully deal with on my end. (And believe me, I tried)

As a result, the only proper solution for now is to release a patch that requires a GeckoLib version between 3.1.6 and 3.1.26, which I have now done with the 1.1.4 update.

Sadly, this is quite literally all I can do for now due to a whole slew of issues with the new GeckoLib updates, and nothing wrong on this mod's end. 😞

**Comment by SplendidAlakey** [comment]
Is it still the case with the newest versions of GeckoLib? They fixed a lot of issues, that the .28 update brought, and most mods in my pack now updated to the latest versions, leaving only Wondrous Wilds.

I really really don't want to play without Wondrous Wilds, so I'll wait as long as it takes, but would just like to know, if the update is now possible, at all.

**Comment by NeffaDev** [comment]
I'm aware that things *should* be fixed in newer GeckoLib versions, but I haven't tested it just yet. If it has been fixed, I will have to update the mod to strictly 1.19.2, as well as update several things, in order to upgrade to the newest GeckoLib version.

If all goes well, you can expect another patch which does all of that to release within the next couple of days 😊

**Comment by NeffaDev** [comment]
Everything went well, and a patch is out now ♥
